config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  resources :notes
  get "login", :to => 'home#login'
  post "login_create", :to => 'home#login_create'
  get 'logout', :to => 'home#logout'
  get 'register', :to => 'users#new'
  resources :users
  get "topics/node_:id" => "topics#node", :as => :node_topics
  get "topics/recent" => "topics#recent", :as => :recent_topics
  get 'setting', :to => 'users#setting', :as => 'setting'
  get 'setting/password', :to => 'users#password', :as => 'password'
  resources :topics do
    member do
      post :reply
    end
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end

  namespace :cpanel do
    root :to => "home#index"
    resources :topics
    resources :sections
    resources :replies
    resources :nodes
    resources :users
    resources :photos
  end

end

app/models/note.rb
# coding: utf-8
# 记事本
class Note < ActiveRecord::Base
  attr_protected :user_id, :changes_count, :word_count
  belongs_to :user, :counter_cache => true

  default_scope -> {order("id desc")}

  before_save :auto_set_value
  def auto_set_value
    if !self.body.blank?
      self.title = self.body.split("\n").first[0..50]
      self.word_count = self.body.length
    end
  end

  before_update :update_changes_count
  def update_changes_count
    self.changes_cout += 1
  end
end

app/controllers/notes_controller.rb
# encoding: utf-8  
class NotesController < ApplicationController
  before_filter :require_user
  # GET /notes
  # GET /notes.xml
  def index
    @notes = @current_user.notes.paginate :page => params[:page], :per_page => 20
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = Note.new(params[:note])
    @note.user_id = @current_user.id

    if @note.save
      redirect_to(@note, :notice => '创建成功。')
    else
      render :action => "new"
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])
    if @note.user_id != @current_user.id
      render_404
    end

    if @note.update_attributes(params[:note])
      redirect_to(@note, :notice => '修改成功。')
    else
      render :action => "edit"
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    if @note.user_id != @current_user.id
      render_404
    end
    @note.destroy

    redirect_to(notes_url)
  end
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <%= render "shared/error_messages", :target => @note %>
  <div class="field">
    <%= f.text_area :body, :class => "long", :style => "height:500px" %>
  </div>
  <div class="actions">
    <button type="submit" class="button submit">保存</button> 或 <a href="<%= notes_path %>">取消</a>
  </div>
<% end %>

app/views/notes/_sidebar.html.erb
<div class="sidebar">
  <div class="box">
    <h2>记事本是什么？</h2>
    <p class="summary">这是一个基于云存储的网络记事本，你可以放心的把你的一些文本资料存放在此处。</p>
    <p>
      <a href="<%= new_note_path %>" class="button">新建</a>
    </p>
  </div>

  <% if ["new","edit"].index(params[:action]) %>
  <div class="box">
    <ul>
      <li>记事的第一行将自动成为标题</li>
      <li>超级链接会自动转换为可点击的状态</li>
      <li>目前只支持纯文本格式</li>
      <li>记事本的内容只有你自己才能看到</li>
    </ul>
  </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<%= content_for :sitemap do %>
  <a href="<%= notes_path %>">记事本</a> &gt;
  <span class="current">修改</span>
<% end %>
<div class="leftbox">
  <div class="notes box">
    <h1>修改记事本</h1>
    <%= render 'form' %>
  </div>
</div>
<%= render "sidebar" %>

app/views/notes/index.html.erb
<%= content_for :sitemap do %>
  <span class="current">记事本</span>
<% end %>
<div class="leftbox clearfix">
  <div id="notes" class="box">
    <h1>我的记事本</h1>
    <div class="total">已有 <%= @current_user.notes_count %> 条记事</div>
    <% if @notes.blank? %>
      <div style="text-align:center; padding:60px 0;">你还没有创建过一个文件。</div>
    <% else %>
      <ul class="list">
      <% @notes.each do |note| %>
        <li>
          <p><a class="title" href="<%= note_path(note.id) %>"><%= truncate(note.title, :length => 50) %></a></p>
          <p class="info"><%= note.word_count %> 个字符, 创建于 <%= time_ago_in_words(note.created_at) %>, <%= note.changes_cout %> 次编辑</p>
        </li>
      <% end %>
      </ul>
    <% end %>
  </div>
</div>
<%= render "sidebar" %>

app/views/notes/new.html.erb
<%= content_for :sitemap do %>
  <a href="<%= notes_path %>">记事本</a> &gt;
  <span class="current">新建</span>
<% end %>
<div class="leftbox">
  <div class="notes box">
    <h1>新建记事本</h1>
    <%= render 'form' %>
  </div>
</div>
<%= render "sidebar" %>

app/views/notes/show.html.erb
<%= content_for :sitemap do %>
  <a href="<%= notes_path %>">记事本</a> &gt;
  <span class="current">查看</span>
<% end %>
<div class="leftbox">
  <div id="notes" class="box">
    <div class="note">
      <div class="body"><%= format_topic_body @note.body %></div>
      <div class="info"><%= @note.word_count %> 个字符, 创建于 <%= time_ago_in_words(@note.created_at) %>, <%= @note.changes_cout %> 次编辑</div>
      <div class="buttons">
        <a href="<%= edit_note_path(@note) %>" class="button submit">编辑</a> &nbsp; &nbsp; &nbsp;
        <%= link_to "删除", note_path(@note),:confirm => "确定要删除吗？", :method => :delete, :class => "button"  %>
      </div>
    </div>
  </div>
</div>
<%= render "sidebar" %>