config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  resources :notes
  get "login", :to => 'home#login'
  post "login_create", :to => 'home#login_create'
  get 'logout', :to => 'home#logout'
  get 'register', :to => 'users#new'
  resources :users
  get "topics/node_:id" => "topics#node", :as => :node_topics
  get "topics/recent" => "topics#recent", :as => :recent_topics
  get 'setting', :to => 'users#setting', :as => 'setting'
  get 'setting/password', :to => 'users#password', :as => 'password'
  resources :topics do
    member do
      post :reply
    end
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end

  namespace :cpanel do
    root :to => "home#index"
    resources :topics
    resources :sections
    resources :replies
    resources :nodes
    resources :users
    resources :photos
  end

end

app/models/topic.rb
#encoding: utf-8
class Topic < ActiveRecord::Base
  validates_presence_of :user_id, :title, :body, :node_id
  belongs_to :node, :counter_cache => true
  belongs_to :user
  belongs_to :last_reply_user, :class_name => "User"

  has_many :replies, :dependent => :destroy#, :include => [:user]

  # scopes
  scope :last_actived, -> {joins(:user, :last_reply_user, :node).order ("replied_at desc, id desc")}

  scope :recents, -> {joins(:user, :last_reply_user, :node).order ("id desc")}

  before_save :set_replied_at

  def set_replied_at
      self.replied_at = Time.now
  end

  # 检查用户是否看过
  # result:
  #   0 读过
  #   1 未读
  #   2 最后是用户的回复
  def user_readed?(user_id)
    uids = Rails.cache.read("Topic:user_read:#{self.id}")
    if uids.blank?
      if self.last_reply_user_id == user_id || self.user_id == user_id
        return 2
      else
        return 1
      end
    end

    if uids.index(user_id)
      return 0
    else
      if self.last_reply_user_id == user_id || self.user_id == user_id
        return 2
      else
        return 1
      end
    end
  end

  # 记录用户读过
  def user_readed(user_id)
    uids = Rails.cache.read("Topic:user_read:#{self.id}")
    if uids.blank?
      uids = [user_id]
    else
      uids = uids.dup
    end

		uids << user_id
    Rails.cache.write("Topic:user_read:#{self.id}",uids)
  end

  # 清除用户读过的记录
  # 用户回复的时候清除状态
  def clear_user_readed
    Rails.cache.write("Topic:user_read:#{self.id}",nil)
  end

end

app/controllers/cpanel/topics_controller.rb
#encoding: utf-8
class Cpanel::TopicsController < Cpanel::ApplicationController
  # GET /topics
  # GET /topics.xml
  def index
    @topics = Topic.includes(:node, :user)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to(cpanel_topics_path, :notice => 'Topic was successfully created.') }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(cpanel_topics_path, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(cpanel_topics_path) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/topics_controller.rb
#encoding: utf-8
class TopicsController < ApplicationController
  before_filter :require_user, :only => [:new,:edit,:create,:update,:destroy,:reply]
  before_filter :init_list_sidebar, :only => [:index,:recent,:cate,:search]

  # GET /topics
  # GET /topics.xml
  def index
    @topics = Topic.last_actived.limit(10)
    @sections = Section.all#.include(:nodes)
    set_seo_meta("社区论坛","#{APP_CONFIG['app_name']}社区,#{APP_CONFIG['app_name']}论坛,#{APP_CONFIG['app_name']}小区论坛,#{APP_CONFIG['app_name']}业主论坛")
  end

  def node
    @node = Node.find(params[:id])
    if @current_user
      Node.set_user_last_visited(@current_user.id, @node.id)
    end
    @topics = @node.topics.last_actived.paginate(:page => params[:page],:per_page => 50)
    set_seo_meta("#{@node.name} &raquo; 社区论坛","#{APP_CONFIG['app_name']}社区#{@node.name}",@node.summary)
    render :action => "index"
  end

  def recent
    @topics = Topic.recents.limit(50)
    set_seo_meta("最近活跃的50个帖子 &raquo; 社区论坛")
    render :action => "index"
  end

  def search
    @topics = Topic.search params[:s], :page => params[:page], :per_page => 50, :include => [:user, :last_reply_user]
    set_seo_meta("搜索#{params[:s]} &raquo; 社区论坛")
    render :action => "index"

  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])
    if @current_user
      Node.set_user_last_visited(@current_user.id, @topic.node_id)
      @topic.user_readed(@current_user.id)
    end
    @node = @topic.node
    @replies = @topic.replies.all
    set_seo_meta("#{@topic.title} &raquo; 社区论坛")
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new
    @topic.node_id = params[:node]
    @node = Node.find(params[:node])
    if @node.blank?
      render_404
    end
     set_seo_meta("发帖子 &raquo; 社区论坛")
  end

  def reply
    @topic = Topic.find(params[:id])
    @reply = @topic.replies.build(params.require(:reply).permit(:body, :state, :source))
    @reply.topic_id = params[:id]
    @reply.user_id = @current_user.id
    if @reply.save
      flash[:notice] = "回复成功。"
    else
      flash[:notice] = @reply.errors.full_messages.join("<br />")
    end
    redirect_to topic_path(params[:id])
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
    if @topic.user_id != @current_user.id
      return render_404
    end
   set_seo_meta("改帖子 &raquo; 社区论坛")
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params.require(:topic).permit(:title, :node_id, :body))
    @topic.user_id = @current_user.id

    if @topic.save
      redirect_to(topic_path(@topic.id), :notice => '帖子创建成功.')
    else
      render :action => "new"
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])
    if @topic.user_id != @current_user.id
      return render_404
    end

    if @topic.update_attributes(params[:topic])
      redirect_to(topics_path, :notice => '帖子修改成功.')
    else
      render :action => "edit"
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    if @topic.user_id != @current_user.id
      return render_404
    end
    @topic.destroy
  redirect_to(topics_path, :notice => '帖子删除成功.')
  end

  private
  def init_list_sidebar
   if !fragment_exist? "topic/init_list_sidebar/hot_nodes.#{params[:format]}"
      @hot_nodes = Node.hots.limit(10)
    end
    if @current_user
      @user_last_nodes = Node.find_last_visited_by_user(@current_user.id)
    end
  end

end

app/helpers/topics_helper.rb
#encoding: utf-8
module TopicsHelper
   def format_topic_body(text,title = "",allow_image = true)
    text = simple_format(h(text))
    if allow_image
      text = text.gsub(/\[img\](http:\/\/.+?)\[\/img\]/,'<img src="\1" alt="'+ h(title) +'" />')
      # if mobile?
        # img_regexp = Regexp.new("<img\s+.*?src=[\"|']?(.*?[^\"'>]+)[\"|']?.*?>", Regexp::IGNORECASE)
        # new_text = text
        # new_text.scan(img_regexp) do |m|
          # img_url = m[0]
          # text = text.gsub(img_url, img_url.gsub("large","small"))
        # end
      # end
    end
    #text = auto_link(text,:all, :target => '_blank', :rel => "nofollow")
    return text
  end

  def topic_use_readed_text(state)
    case state
    when 0
      "在你读过以后还没有新变化"
    else
      "有新内容"
    end
  end
end

app/views/topics/_base.html.erb
<% content_for :styles do %>
   <%=stylesheet_link_tag "topics", :cache => "cached_topics" %>
<% end %>

app/views/topics/_form.html.erb
<% content_for :scripts do %>
<script type="text/javascript">
	function appendImageFromUpload(srcs){
     txtBox = $(".topic_body_text_area");
     for(var i=0;i<srcs.length;i++){
       txtBox.val(txtBox.val() + '[img]'+srcs[i]+'[/img]\n');
     }
     txtBox.focus();
     $("#add_image").jDialog.close();
   }

   function addImageClick(){
     $("#add_image").jDialog({
       title:"插入图片",
       width:"350",
       height:"130",
       content: '<iframe src="<%= tiny_new_photos_path %>" frameborder="0" style="width:330px; height:130px;"></iframe>',
       close_on_body_click : false
     });
     return false;
   }
</script>
<% end %>
<%= form_for(@topic, :url => (@topic.id.blank? ? topics_path : topic_path(@topic.id))) do |f| %>
  <%= render "shared/error_messages", :target => @topic %>
  <%= f.hidden_field :node_id %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :class => "middle" %>
  </div>
  <div class="field">
    <div class="edit_tools">
			<a href="#" onclick="return addImageClick();" id="add_image">上传图片</a>
		</div>
    <%= f.label :body %><br />
    <%= f.text_area :body, :class => "topic_body_text_area long", :style => "height:400px" %>
  </div>
  <div class="actions">
    <button class="button submit">保存</button>
  </div>
<% end %>

app/views/topics/_sidebar.html.erb
<div class="sidebar">
	<% if ["show","new"].index(params[:action]) %>
  <div class="box">
    <h2><a href="<%= node_topics_path(@node) %>"><%= @node.name %></a></h2>
    <% if ["new"].index params[:action] %>
    <p class="sumamry">
      <%= @node.summary %>
    </p>
    <% end %>
    <div class="content">
      <a class="button super" href="<%= new_topic_path(:node => @node.id) %>">发布新帖</a>
    </div>
  </div>
<% elsif params[:action] == "index" %>
  <div class="box">
    <h2>社区论坛</h2>
    <p>
      这里是<%= APP_CONFIG['app_name'] %>社区论坛，大家可以在这里讨论于社区有关的话题。
    </p>
    <p>
      发贴请先进入一个节点以后点击“发布新帖”。
    </p>
  </div>
<% end %>
<% cache("topic/init_list_sidebar/hot_nodes",:expires_in => 30.minutes) do %>
  <% if not @hot_nodes.blank? %>
  <div class="hot_nodes nodes box">
    <h2>热门节点</h2>
    <p>
      <% @hot_nodes.each do |node| %>
        <a href="<%= node_topics_path(:id => node.id) %>"><%= node.name %></a>
      <% end %>
    </p>
  </div>
  <% end %>
<% end %>
<% if @current_user and (not @user_last_nodes.blank?) %>
<div class="user_last_nodes nodes box">
  <h2>最近访问节点</h2>
  <p>
    <% @user_last_nodes.each do |node| %>
      <a href="<%= node_topics_path(:id => node.id) %>"><%= node.name %></a>
    <% end %>
  </p>
</div>
<% end %>
<% if ["new"].index(params[:action]) %>
  <div class="box">
    <h2>发贴说明</h2>
    <ol>
      <li>发布后正文排版会自动根据你在文本框里面输入的样子排列.如果里面带有 URL地址，将会自动转变为超级链接。</li>
      <li>当然，作为一个社区，插图功能自然不会少，可以点击“上传图片”来发图。</li>
      <li>强烈建议你在提交之前再次确认一下是否还有需要修改的地方，因为我们暂时没有给你提供后期修改的功能。</li>
    </ol>
  </div>
<% end %>

</div>

app/views/topics/edit.html.erb
<%= render 'base' %>
<% content_for :sitemap do %>
  <span class="current">修改</span>
<% end %>
<div class="leftbox">
	<div class="box">
    <h1>修改贴子</h1>
     <%= render 'form' %>
	</div>
</div>
<%= render 'sidebar' %>

app/views/topics/index.html.erb
<%= render 'base' %>
<% content_for :sitemap do %>
  <% if params[:action] == "node" %>
    <span class="current"><%= h @node.name %></span>
  <% elsif params[:action] == "recent" %>
    <span class="current">最近活跃的50个主题</span>
  <% elsif params[:action] == "search" %>
    <span class="current">搜索<%= h params[:s] %></span>
  <% else %>
    <span class="current">活跃帖子</span>
  <% end %>
<% end %>
<div class="leftbox">
	<div class="box">
	<% if !@node.blank? %>
    <div id="node_info">
      <p>
        <h1><%= h @node.name %></h1>
        <span class="total">共有 <%= @node.topics_count %> 个讨论主题</span>
      </p>
      <p class="summary"><%= h @node.summary %></p>
      <p>
      <a class="button super" href="<%= new_topic_path(:node => @node.id) %>">发布新帖</a>
      </p>
    </div>
    <% else %>
      <h1><%= APP_CONFIG['app_name'] %>社区论坛</h1>
    <% end %>
    <% if params[:action] == "node" %>
      <table class="node_topics">
        <tr class="head">
          <td class="replies">回复数</td>
          <td class="title">标题</td>
          <td class="author">作者</td>
          <td class="replied_at">最后回复时间</td>
        </tr>
        <% @topics.each do |topic| %>
        <tr class="topic">
          <td class="replies"><%= topic.replies_count %></td>
          <td class="title"><a href="<%= topic_path(topic) %>"><%= truncate(topic.title, :length => 25) %></a></td>
          <td class="author"><%= user_name_tag(topic.user) %></td>
          <td class="replied_at"><%= l (topic.replied_at || topic.created_at), :format => :short %></td>
        </tr>
        <% end %>
      </table>
    <% else %>
      <table class="topics">
      <% @topics.each do |topic| %>
      <tr class="topic">
        <td class="avatar">
          <%= image_tag(topic.user.avatar(:normal)) %>
        </td>
        <td>
          <p class="title"><a href="<%= topic_path(topic) %>" title="<%= topic.title %>"><%= truncate(topic.title, :length => 100) %></a></p>
          <p class="info leader">
            由 <a href="<%= user_path(topic.user_id) %>"><%= topic.user.name %></a>
            在 <a href="<%= node_topics_path(topic.node_id) %>"><%= topic.node.name %></a> 中发起
          </p>
          <p class="info time">
            <% if topic.last_reply_user.blank? %>
              发布于 <%= time_ago_in_words(topic.created_at) %>前
            <% else %>
              最后由 <a href="<%= user_path(topic.last_reply_user_id) %>"><%= topic.last_reply_user.name %></a> 回复于 <%= time_ago_in_words(topic.replied_at) %>前
            <% end %>
          </p>
        </td>
        <td class="replies">
          <% readed_state = topic.user_readed?(@current_user.id) if @current_user %>
          <a href="<%= topic_path(topic.id) %>" title="<%= topic_use_readed_text(readed_state) if @current_user %>" class="count state<%= readed_state if @current_user %>">
          <%= topic.replies_count %>
          </a>
        </td>
      </tr>
      <% end %>
      </table>
    <% end %>

    <% if params[:action] == "index" %>
      <div class="more">
        <a href="<%= recent_topics_path %>">查看更多最近发布的帖子...</a>
      </div>
    <% elsif params[:action] == "node" or params[:action] == "search" %>
      <%= will_paginate @topics %>
    <% end %>
<% if params[:action] == "index" %>
	<div id="sections" class="box">
	<h2>讨论节点分类导航</h2>
	<ul>
		<% @sections.each do |section| %>
		<li>
			<label><%= section.name %></label>
			<% section.nodes.each do |node| %>
			<a href="<%= node_topics_path(node.id) %>" title="<%= node.name %>"><%= node.name %></a>
			<% end %>
		</li>
		<% end %>
	</ul>
	</div>
	<% end %>
	</div>
</div>
<%= render 'sidebar' %>

app/views/topics/new.html.erb
<% render 'base' %>
<% content_for :sitemap do %>
  <span class="current">新建贴子</span>
<% end %>
<div class="leftbox">
	<div class="box">
      <h1>新建贴子</h1>
      <%= render 'form' %>
  </div>
</div>
<%= render 'sidebar' %>

app/views/topics/show.html.erb
<%= render 'base' %>
<% content_for :sitemap do %>
  <a href="<%= node_topics_path(@topic.node_id) %>"><%= @topic.node.name %></a> &gt;
  <span class="current">查看贴子</span>
<% end %>

<div class="leftbox">
	<div class="topics box">
		<table>
			<tr class="topic noborder">
		    <td>
					<h1><%= truncate(@topic.title, :length => 100) %></h1>
					<p class="info leader">
						由 <a href="<%= user_path(@topic.user_id) %>"><%= @topic.user.name %></a>
						在 <%= @topic.node.name %> 中发起
					</p>
					<p class="info time">
						<% if @topic.last_reply_user.blank? %>
							发布于 <%= time_ago_in_words(@topic.created_at) %>
						<% else %>
							最后由 <a href="<%= user_path(@topic.last_reply_user_id) %>"><%= @topic.last_reply_user.name %></a> 回复于 <%= time_ago_in_words(@topic.replied_at) %>
						<% end %>
					</p>
				</td>
        <td class="avatar">
					<%= image_tag(@topic.user.avatar(:normal)) %>
				</td>
		  </tr>
		</table>
    <div class="body">
			<%= format_topic_body(@topic.body) %>
		</div>
	</div>
  <% if @replies.blank? %>
    <div class="no_result">
      暂无回复。
    </div>
  <% else %>
  <div id="replies" class="box">
    <div class="total">
      截止 <%= l @topic.replied_at, :format => :default %> 共收到 <%= @topic.replies_count %> 条回复
    </div>
    <% @replies.each_with_index do |reply,i| %>
      <div class="reply">
      <table>
       <tr>
          <td class="face"><%= user_avatar_tag(reply.user, :normal) %></td>
          <td>
            <div class="info clearfix">
              <span class="name"><%= user_name_tag(reply.user) %></span>
              <span class="time">回复于 <%= time_ago_in_words(reply.created_at) %>前, #<%= i + 1 %></span>
            </div>
            <div class="body">
              <%= format_topic_body(reply.body,"",false) %>
            </div>
          </td>
        </tr>
      </table>
      </div>
    <% end %>
  </div>
  <% end %>
  <div id="reply" class="form box">
    <%= notice_message %>
    <h2>回复</h2>
    <%= form_for(Reply.new,:url => reply_topic_path(params[:id])) do |f| %>
      <div class="field">
        <%= f.text_area :body,:class => "long", :style => "height:80px;" %>
      </div>
      <div class="buttons">
        <button type="submit" class="button submit">提交回复</button>
      </div>
    <% end %>
  </div>
</div>
<%= render 'sidebar' %>