config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  resources :notes
  get "login", :to => 'home#login'
  post "login_create", :to => 'home#login_create'
  get 'logout', :to => 'home#logout'
  get 'register', :to => 'users#new'
  resources :users
  get "topics/node_:id" => "topics#node", :as => :node_topics
  get "topics/recent" => "topics#recent", :as => :recent_topics
  get 'setting', :to => 'users#setting', :as => 'setting'
  get 'setting/password', :to => 'users#password', :as => 'password'
  resources :topics do
    member do
      post :reply
    end
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end

  namespace :cpanel do
    root :to => "home#index"
    resources :topics
    resources :sections
    resources :replies
    resources :nodes
    resources :users
    resources :photos
  end

end

app/controllers/cpanel/home_controller.rb
#encoding: utf-8
class Cpanel::HomeController < Cpanel::ApplicationController
  def index
    @recent_topics = Topic.recents.limit(5)
  end
end

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController
  before_filter :require_no_user, :only => [:login, :login_create]
  before_filter :require_user, :only => :logout

  def index
    if @current_user
      redirect_to topics_path
    end
  end

  def login
    @user_session = UserSession.new
  end

  def login_create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_back_or_default root_path
    else
      render :action => :login
    end
  end

  def logout
    current_user_session.destroy
    redirect_back_or_default root_path
  end

end

app/views/home/index.html.erb
<% content_for :sitemap do %><span class="current">首页</span><% end %>
<div id="home_index" class="box">
  <h1>Ruby Blog</h1>
  <p>
    这里是ruby论坛。
  </p>
  <h2>为什么要建立这个论坛？</h2>
  <p>
    Ruby is my 1st dev language.<br />
  </p>
</div>

app/views/home/login.html.erb
<%= content_for :sitemap do %><span class="current">登录</span><% end %>
<div class="leftbox">
  <div class="box">
  <h1>登录<%= APP_CONFIG['app_name'] %></h1>
  <div class="form">
  <%= form_for :user_session, :url => login_create_path do |f| %>
    <%= render "shared/error_messages", :target => @user_session %>
    <div class="field">
    <%= f.label :email, "Email:" %><br />
    <%= f.text_field :email %>
    </div>
    <div class="field">
    <%= f.label :password, "密码:" %><br />
    <%= f.password_field :password %>
    </div>
    <div class="field">
    <%= f.check_box :remember_me, :class => "checkbox" %><%= f.label :remember_me, "一月之内不用再次登录" %><br />
    </div>
    <p>
    <button type="submit" class="button submit">登录</button> 或 <a href="<%= new_user_path %>">注册新用户</a>
    </p>
  <% end %>
  </div>
</div>
</div>
<div class="sidebar">
  <div class="box">
    <h2>没有帐号吗？</h2>
    <p>
      <a href="<%= register_path %>">现在就注册一个</a>
    </p>
  </div>
</div>